databases:
  - name: estoque-db
    plan: free          # para banco pode manter "free"
    databaseName: estoque
    user: app
    # NÃ£o definir diskSizeGB no plano free
    # postgresMajorVersion: "17"  # opcional

services:
  - type: web
    name: estoque-backend
    runtime: docker
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: estoque-db
          property: connectionString
      - key: TZ
        value: America/Sao_Paulo
    healthCheckPath: /docs

  - type: web
    name: estoque-frontend
    runtime: static
    staticPublishPath: frontend
    # (Opcional) se quiser usar /api/... em vez da URL completa do backend:
    # routes:
    #   - type: rewrite
    #     source: /api/(.*)
    #     destination: https://SEU-BACKEND.onrender.com/$1

