databases:
  - name: estoque-db
    databaseName: estoque
    user: app
    plan: starter
    diskSizeGB: 10
    postgresMajorVersion: "17"

services:
  - type: web
    name: estoque-backend
    runtime: docker
    plan: starter
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: estoque-db
          property: connectionString
      - key: TZ
        value: America/Sao_Paulo
    healthCheckPath: /docs

  - type: web
    name: estoque-frontend
    runtime: static
    staticPublishPath: frontend
    # (opcional) se quiser usar /api/... no frontend em vez de URL completa do backend:
    # routes:
    #   - type: rewrite
    #     source: /api/(.*)
    #     destination: https://SEU-BACKEND.onrender.com/$1
